export {};
export const test1 = 1;
export const test2 = 2;
export const test3 = 3;
export const test4 = 4;
export const test5 = 5;
export const test6 = 6;
export const test7 = 7;
export const test8 = 8;
export const test9 = 9;
export const qwe1 = 1;
